#!/usr/bin/env python3
"""Embed an MJCF file into the guest as a C string.

The guest has no filesystem and, once the flat arena is off so the machine can
be serialised, no working host-to-guest transfer either. A model that ships
inside the binary needs neither.

    python scripts/embed_model.py <model.xml> <out.h>
"""

import pathlib
import sys


def emit(xml_path, out_path):
    xml = pathlib.Path(xml_path).read_text(encoding="utf-8")
    body = "".join(
        '\t"' + line.replace("\\", "\\\\").replace('"', '\\"') + '\\n"\n'
        for line in xml.splitlines()
    )
    out = (
        "// Generated by scripts/embed_model.py. Edit the .xml, not this file.\n"
        "#pragma once\n\n"
        "static const char MODEL_XML[] =\n" + body + "\t;\n"
    )
    pathlib.Path(out_path).write_text(out, encoding="utf-8", newline="\n")


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    emit(sys.argv[1], sys.argv[2])
    return 0


if __name__ == "__main__":
    sys.exit(main())
